# image-updater-cr.yml
apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: chai-app-updater
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: "chai-app"
      useAnnotations: true
